In [2]:
## Unzipping File
import zipfile
with zipfile.ZipFile("../data/raw/Archive.zip", "r") as zip_ref:
    zip_ref.extractall("../data/raw")

In [3]:
del zip_ref

In [3]:
data = {
    'customer': ['Anna', 'David'],
    'revenue': [100, 180]
}
df = pd.DataFrame(data)

In [1]:
## Import packages
import pandas as pd
import numpy as np

In [7]:
# Reading data
df_orders = pd.read_csv('../data/raw/orders.csv', 
                        # usecols= ['order_id', 'user_id','order_hour_of_day', 'days_since_prior_order']
                        )
df_products = pd.read_csv('../data/raw/orders.csv')

In [6]:
df_orders.rename(columns={'order_n': 'order_number'})

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0
...,...,...,...,...,...,...,...
3421078,2266710,206209,prior,10,5,18,29.0
3421079,1854736,206209,prior,11,4,10,30.0
3421080,626363,206209,prior,12,1,12,18.0
3421081,2977660,206209,prior,13,1,12,7.0
3421082,272231,206209,train,14,6,14,30.0

In [6]:
list(df.columns)

['customer', 'revenue']

In [10]:
df_orders.columns

Index(['order_id', 'user_id', 'eval_set', 'order_number', 'order_dow',
       'order_hour_of_day', 'days_since_prior_order'],
      dtype='str')

In [13]:
df_products.columns

Index(['order_id', 'user_id', 'eval_set', 'order_number', 'order_dow',
       'order_hour_of_day', 'days_since_prior_order'],
      dtype='str')

In [15]:
df_products.info()

<class 'pandas.DataFrame'>
RangeIndex: 3421083 entries, 0 to 3421082
Data columns (total 7 columns):
 #   Column                  Dtype
---  ------                  -----
 0   order_id                int64
 1   user_id                 int64
 2   eval_set                str
 3   order_number            int64
 4   order_dow               int64
 5   order_hour_of_day       int64
 6   days_since_prior_order  float64
dtypes: float64(1), int64(5), str(1)
memory usage: 182.7 MB

In [18]:
df_orders.dtypes

order_id                    int64
user_id                     int64
eval_set                      str
order_number                int64
order_dow                   int64
order_hour_of_day           int64
days_since_prior_order    float64
dtype: object

In [19]:
df_products.describe()

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
count,3.421083e+06,3.421083e+06,3.421083e+06,3.421083e+06,3.421083e+06,3.214874e+06
mean,1.710542e+06,1.029782e+05,1.715486e+01,2.776219e+00,1.345202e+01,1.111484e+01
std,9.875817e+05,5.953372e+04,1.773316e+01,2.046829e+00,4.226088e+00,9.206737e+00
min,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,8.552715e+05,5.139400e+04,5.000000e+00,1.000000e+00,1.000000e+01,4.000000e+00
50%,1.710542e+06,1.026890e+05,1.100000e+01,3.000000e+00,1.300000e+01,7.000000e+00
75%,2.565812e+06,1.543850e+05,2.300000e+01,5.000000e+00,1.600000e+01,1.500000e+01
max,3.421083e+06,2.062090e+05,1.000000e+02,6.000000e+00,2.300000e+01,3.000000e+01

In [11]:
df_orders_new = df_orders.assign(
    is_weekend = df_orders['order_dow'].isin([0, 6]),
    is_morning = df_orders['order_hour_of_day'] < 12
)

In [24]:
df_orders_new.tail()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,is_weekend,is_morning
3421078,2266710,206209,prior,10,5,18,29.0,False,False
3421079,1854736,206209,prior,11,4,10,30.0,False,True
3421080,626363,206209,prior,12,1,12,18.0,False,False
3421081,2977660,206209,prior,13,1,12,7.0,False,False
3421082,272231,206209,train,14,6,14,30.0,True,False

In [ ]:
df_orders['order_frequency_category'] = df_orders['order_number'].apply(
    lambda x: "New" if x == 1
    else "Low" if x <= 5
    else "High"
)